version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME:-local}/hymn-scanner-backend:latest
    build: .
    ports:
      - "8654:8654"
    env_file:
      - .env
    volumes:
      - ./appdata_index:/root/HymnScanner/
    networks:
      - npm_net

  frontend:
    image: ${DOCKER_USERNAME:-local}/hymn-scanner-frontend:latest
    build: ./frontend
    ports:
      - "4789:80"
    networks:
      - npm_net

networks:
  npm_net:
    external: true
    name: crms_stack_crms-net
