version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME:-local}/hymn-scanner-backend:latest
    build: .
    ports:
      - "8654:8654"
    volumes:
      - ./.env:/root/HymnScanner/.env
      - ./appdata_index:/root/HymnScanner/

  frontend:
    image: ${DOCKER_USERNAME:-local}/hymn-scanner-frontend:latest
    build: ./frontend
    ports:
      - "4789:4789"
